MACHINE_ISSUE_STATUS_OPEN = "Open"
MACHINE_ISSUE_STATUS_URGENT = "Urgent"
MACHINE_ISSUE_STATUS_RESOLVED = "Resolved"
MACHINE_ISSUE_STATUS_CLOSED = "Closed"


MACHINE_ISSUE_STATUS = (
    (MACHINE_ISSUE_STATUS_OPEN, "OPEN"),
    (MACHINE_ISSUE_STATUS_URGENT, "URGENT"),
    (MACHINE_ISSUE_STATUS_RESOLVED, "RESOLVED"),
    (MACHINE_ISSUE_STATUS_CLOSED, "CLOSED"),
)
